version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 20
    groups:
      minor-patch-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "America/New_York"
    target-branch: "develop"
    reviewers:
      - "@DataBiosphere/platform-foundation-codeowners"
    labels:
      - "dependency"
      - "gradle"
    commit-message:
      prefix: "[PF-2983]"
    ignore:
      # PF-3000: k8s client versions 20.0.0 onward without '-legacy' suffix include breaking changes
      - dependency-name: "io.kubernetes:client-java"
