# Copied from https://github.com/DataBiosphere/terra-aws-resource-discovery/tree/main
# TODO(TERRA-418) Move this to https://github.com/DataBiosphere/github-actions
# This action must be done after the checkout action
name: 'setup-gradlew'
description: 'Checkout code and setup gradlew'

runs:
  using: 'composite'

  steps:
  - name: Set up JDK 17
    uses: actions/setup-java@v3
    with:
      java-version: '17'
      distribution: 'temurin'

  - name: Cache Gradle packages
    uses: actions/cache@v3
    with:
      path: |
        ~/.gradle/caches
        ~/.gradle/wrapper
      key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
      restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}

  - name: Add execute permissions to gradle
    shell: bash
    run: chmod +x gradlew
