name: development version bump
on:
  push:
    branches: [ develop ]
    paths-ignore: [ '**.md' ]
  workflow_dispatch: { }

jobs:
  publish_snapshot:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432

    steps:
    - name: Checkout current code
      uses: actions/checkout@v3
      with:
        ref: develop
        token: ${{ secrets.BROADBOT_GITHUB_TOKEN }}

    - name: Skip version bump merges
      id: bump-skip
      uses: ./.github/actions/bump-skip
      with:
        event-name: ${{ github.event_name }}

    - name: Initialize Postgres DB
      env:
        PGPASSWORD: postgres
      run: psql -h 127.0.0.1 -U postgres -f ./local-dev/local-postgres-init.sql

    - name: Setup gradlew
      uses: ./.github/actions/setup-gradlew

    - name: Build, assemble, and test
      id: build-assemble-test
      run: ./gradlew build
    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Test Reports
        path: build/reports

    - name: "Bump the tag to a new version"
      if: steps.bump-skip.outputs.is-bump == 'no'
      uses: databiosphere/github-actions/actions/bumper@bumper-0.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        RELEASE_BRANCHES: develop
        VERSION_FILE_PATH: settings.gradle
        VERSION_LINE_MATCH: "^\\s*gradle.ext.tclVersion\\s*=\\s*'.*'"
        VERSION_SUFFIX: SNAPSHOT

    - name: "Publish to Artifactory"
      if: steps.bump-skip.outputs.is-bump == 'no'
      run: ./gradlew artifactoryPublish
      env:
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        ARTIFACTORY_REPO_KEY: "libs-snapshot-local"
