name: development version bump
on:
  push:
    branches: [ develop ]
    paths-ignore: [ '**.md' ]
  workflow_dispatch: {}

jobs:
  publish_snapshot:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
          token: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
      - name: Initialize Postgres DB
        env:
          PGPASSWORD: postgres
        run: psql -h 127.0.0.1 -U postgres -f ./local-dev/local-postgres-init.sql
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      # See https://github.com/actions/cache/blob/main/examples.md#java---gradle
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build, assemble, and test
        id: build-assemble-test
        run: ./gradlew build
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: Test Reports
          path: build/reports
      - name: "Bump the tag to a new version"
        uses: databiosphere/github-actions/actions/bumper@bumper-0.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: develop
          VERSION_FILE_PATH: build.gradle
          VERSION_LINE_MATCH: ^version
          VERSION_SUFFIX: SNAPSHOT
      - name: "Publish to Artifactory"
        run: ./gradlew artifactoryPublish
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          ARTIFACTORY_REPO_KEY: "libs-snapshot-local"
