name: Publish package to Release Artifactory
on:
  release:
    types: [created]
jobs:
  publish_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run unit tests
        id: unit-test
        run: ./gradlew unitTest --scan
      - name: Run integration tests
        id: integration-test
        run: ./gradlew integrationTest --scan
#      TODO(yonghao): add this back once we have test
#      - name: Upload Test Reports
#        if: always()
#        uses: actions/upload-artifact@v1
#        with:
#          name: Test Reports
#          path: build/reports/tests
      - name: "Bump the tag to a new version"
        uses: databiosphere/github-actions/actions/bumper@v0.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master,develop
          VERSION_FILE_PATH: build.gradle
          VERSION_LINE_MATCH: ^version
          VERSION_SUFFIX: SNAPSHOT
      - name: "Publish to Artifactory"
        uses: broadinstitute/gradle-command-action@v1
        with:
          arguments: artifactoryPublish
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          ARTIFACTORY_REPO_KEY: "libs-release-local"
